### ISSUE TITLE
 Error does not extract manifest.sii in version 29-08

### ISSUE THREAD

**Issue by mario50245** [sk-zk/Extractor#11]
Hello how are you?? In the 08-29 version it throws an error when extracting manifest.sii from any bus or truck but I tried it with the 07-15 version and if it works I attach the evidence

Evidence version 29-08 : 

![image](https://github.com/user-attachments/assets/5ecda1e2-d600-4457-8658-1c75d485be13)

Evidence version 15-07 

![image](https://github.com/user-attachments/assets/a0cdd624-add4-4d49-a84a-d8e5f7a33418)

**Comment by sk-zk** [comment]
Fixed in 2024-09-02
