### ISSUE TITLE
HashFS V2 Error

### ISSUE THREAD

**Issue by n4vi98** [sk-zk/Extractor#15]
Hi I got this error from a .tobj file and the result DDS file is 0kb in size the actual is 21mb, but in scs_extractor it extracts just fine without corrupted files..

[Error.txt](https://github.com/user-attachments/files/17487035/Error.txt)

Extracting arhieve.scs/vehicle/trailer_owned/trailer/cargo/bc2100xlpm/ ...
Unable to extract vehicle/trailer_owned/trailer/cargo/bc2100xlpm/burshchipperpart3normalclean.tobj:
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length')) (Specified argument was out of the range of valid values. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.Range.ThrowArgumentOutOfRangeException()
   at GisDeflate.Deflate.TileDecompressionJob(DecompressionContext, Byte[], Int32[])
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)

**Comment by sk-zk** [comment]
Link to the mod?

**Comment by n4vi98** [comment]
> Link to the mod?

https://modsfire.com/vG8q4m526j26T92
https://mods.to/QJiL67187ac0254c7

**Comment by sk-zk** [comment]
Fixed in 2024-10-24
