### ISSUE TITLE
Error using -p

### ISSUE THREAD

**Issue by mario50245** [sk-zk/Extractor#18]
Hello There is an error when extracting the def in the new update. I attach the evidence

Version 24-10

![image](https://github.com/user-attachments/assets/cb0303bd-3758-4e7c-a47a-244aa5ef73ff)

![image](https://github.com/user-attachments/assets/ebb3e1c6-cce2-4704-91f8-18659c724d34)
 
Version 01-10

0 Problem

![image](https://github.com/user-attachments/assets/0c1e058e-91b6-4846-83b4-928b02aa6dc2)

![image](https://github.com/user-attachments/assets/b2df64cb-c86f-4b94-bf4e-ecf059d6885d)

![image](https://github.com/user-attachments/assets/db71d65c-6d11-4313-adeb-1346c70e790a)

****************** 

The other thing is there a way to completely unlock the mod. Not in parts because I tried with another mod (Map) and managed to unlock folder by folder but generate an error when editing the map and finally nothing can be done.....

**Comment by BonzTM** [comment]
> Yeah, I discovered this issue yesterday. Will be fixed in the next release.
> 
> > The other thing is there a way to completely unlock the mod. Not in parts because I tried with another mod (Map) and managed to unlock folder by folder but generate an error when editing the map and finally nothing can be done.....
> 
> I've actually started working on this a week ago. There'll be a `--deep` mode in the near future which will restore paths automatically so you won't have to do it step by step anymore.

Is the future `--deep` functionality intended to replace any third-party `Pathfinder` tools?
