### ISSUE TITLE
Another possibly "obfuscated" mod

### ISSUE THREAD

**Issue by DrmnSamoLiu** [sk-zk/Extractor#3]
I recently got into the world of ETS2 and I'm lovin' it. With the recent v1.5 update that broke a lot of mod tools I stumbled upon your nice extractor project :)

Here is a Mazda Miata mod that I'm trying to extract and change the super dark windshield tint:
https://forum.scssoft.com/viewtopic.php?t=312737

But both official v1.50 extractor and your extractor failed to extract it, showing "not supported file format".
It works fine in the v1.5 game though, so the .scs file is definitely not corrupted.
I saw from the closed issues that there were quite some mods that seems to be "obfuscated" so it cannot be extracted, I wonder if this is the same case.
Also if it really is obfuscation, how does it even work in game? That's really amazing to think of.

**Comment by sk-zk** [comment]
The file in question is not a HashFS file, but one of those weird "locked" zip files, so it falls outside the scope of this tool. I don't know how this little trick works and people are being rather cagey about it, but I managed to dig up [this old tool](https://github.com/sislamoglu/SCS_Unlocker/blob/bin/MainProgram/Delphi/Release/win_x86/SCS_Unlocker.exe) which may or may not work (I don't have Wine installed at the moment, so I can't check).

**Comment by sk-zk** [comment]
Good news: I've changed my mind on this as I was looking into #13 and implemented ZIP support after all. The latest version of my extractor can now unzip this file.
