### ISSUE TITLE
Error hash 

### ISSUE THREAD

**Issue by mario50245** [sk-zk/Extractor#6]
![image](https://github.com/user-attachments/assets/8db08cfd-258d-4907-8894-087ae1fb6868) 

Hello, this error appears on a Turkish bus.
 
https://modsfire.com/r8u1C82PImjH4y0 

https://sharemods.com/t4vxph04cibm/Temsa_Safir_Plus_1_50_X_KskLi1453.7z.html

**Comment by sk-zk** [comment]
Fixed in 2024-07-15
