### ISSUE TITLE
Problem with .pmg files when extracting

### ISSUE THREAD

**Issue by Mahyar378** [sk-zk/Extractor#8]
hello

I wanted to open a .scs using Extractor.
The directories were hidden, I gave the list of directories with the help of -P and executed.
The files were extracted, but the size of all .pmg files is the same and 512KB

![image](https://github.com/user-attachments/assets/1dd04fb6-b0c2-4e19-a102-ac573813cff4)

what is the problem?

**Comment by sk-zk** [comment]
Can you post a link to the mod?

**Comment by Mahyar378** [comment]
yes of course

Link:
https://sharemods.com/v0f8kbgdl7ud/New-Travego-16SHD_1_50_X_KskLi1453.7z.html

**Comment by sk-zk** [comment]
This mod uses an invisible Unicode character in several of its paths and additionally contains decoy entries to obscure this fact.

Let's take a random .sii file containing a path to a .pmd file and paste it into a Unicode analyzer:

<img src="https://i.imgur.com/55B2lYP.png" width=200>

As you can see, there is an invisible character, U+2062, at the end of each directory name. This character must be included in the path passed to the extractor to get the actual model. If this character is missing, you get the decoy files as shown in your screenshot.
